CREATE DATABASE IF NOT EXISTS FlashFeet_JohnMc;
DELIMITER $$
DROP PROCEDURE IF EXISTS CreateDatabase $$
CREATE PROCEDURE CreateDatabase()
BEGIN
  START TRANSACTION;
USE FlashFeet_JohnMc;

CREATE TABLE IF NOT EXISTS JobRole(
	jobRole VARCHAR(70) PRIMARY KEY,
);

END $$
DELIMITER ;
CALL CreateDatabase();
