CREATE DATABASE IF NOT EXISTS FlashFeet_JohnMc;
USE FlashFeet_JohnMc;

DELIMITER $$
DROP PROCEDURE IF EXISTS CreateJobRoleTable $$
CREATE PROCEDURE CreateJobRoleTable()
BEGIN
  
CREATE TABLE IF NOT EXISTS JobRole(
	jobRole VARCHAR(70) PRIMARY KEY
);

END $$
DELIMITER ;
CALL CreateJobRoleTable();
