CREATE DATABASE IF NOT EXISTS FlashFeet_BreannaL;
USE FlashFeet_BreannaL;

DELIMITER $$
DROP PROCEDURE IF EXISTS CreateDatabase $$
CREATE PROCEDURE CreateDatabase()
BEGIN
  
CREATE TABLE IF NOT EXISTS JobRole(
	jobRole VARCHAR(70) PRIMARY KEY
);

END $$
DELIMITER ;
CALL CreateDatabase();
